#title in header
title: "Hello!"

#main info
#owner
owner: "Ziqian Xu"
email: zxu9@nd.edu
info: ""
#description
desc: "I am a current graduate student at the University of Notre Dame studying Quantitative Psychology. My research interest mainly lies in social network analysis and longitudinal data analysis. I am also interested in various data visualization techniques and machine learning. In my free time, I play Genshin a lot, and I love animes such as Attack on Titan and Neon Genesis Evangelion. "

#menu
menu:
  About: /About
  Works: /Works
  Experience: /Experience


#index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Earth
placelink: https://en.wikipedia.org/wiki/Earth
github: https://github.com/adisaktijrs
linkedin: https://linkedin.com/in/adisaktijrs
twitter: https://twitter.com/adisaktijrs
instagram: https://instagram.com/adisaktijrs
stackoverflow: https://stackoverflow.com/story/tobiasreithmeier

# Misc
nanobar: /js/nanobar.min.js
switch_light: ☀️
switch_dark: 🌑

# Picture enlargement
picjs: /js/pic.min.js

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-adisaktijrs-github-io
